- hosts: install_docker
  become: yes
  gather_facts: false
  tasks:
  - name: Install docker packages
    remote_user: tcude
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    tags:
      - docker
  - name: Add Docker s official GPG key
    remote_user: tcude
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    tags:
      - docker
  - name: Verify that we have the key with the fingerprint
    remote_user: tcude
    apt_key:
      id: 0EBFCD88
      state: present
    tags:
      - docker
  - name: Set up the stable repository
    remote_user: tcude
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      state: present
      update_cache: yes
    tags:
      - docker
  - name: Update apt packages
    remote_user: tcude
    apt:
      update_cache: yes
    tags:
      - docker
  - name: Install docker
    remote_user: tcude
    apt:
      name: docker-ce
      state: present
      update_cache: yes
    #notify: Start docker on boot
    tags:
      - docker
  - name: Add remote "tcude" user to "docker" group
    remote_user: tcude
    user:
      name: "tcude"
      group: "docker"
      append: yes
    tags:
      - docker
  - name: Install docker-compose
    remote_user: tcude
    apt:
      name: docker-compose
      state: present
      update_cache: yes
    tags:
      - docker
