---
- name: install packages
  hosts: ubuntu
  become: true
  vars:
    user:
      - name: "tcude"
    packages:
      - neofetch
      - qemu-guest-agent
      - htop
      - ncdu
      - snmpd 
  tasks:
  - name: install packages
    apt:
      name: "{{ packages }}"
      state: present
