- hosts: "*"
  become: yes
  vars:
    user:
      - name: "tcude"
    packages:
      - wget
      - scdu
      - htop
      - neofetch

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
    - name: Ensure a list of packages installed
      update_cache: yes
      package:
        name: "{{ packages }}"
        state: latest
    - name: All done!
      debug:
        msg: All packages have been successfully installed
