---
- name: install packages
  hosts: install_docker
  become: true
  vars:
    user:
      - name: "tcude"
    packages:
      - neofetch
      - htop
  tasks:
  - name: install packages
    apt:
      name: "{{ packages }}"
      state: present
