- hosts: "*"
  become: yes
  tasks:
      - name: copy
        copy:
            src: "/home/{{ item.username }}/ansible/pub_key/id_rsa.pub"
            dest: "/home/{{ item.username }}/.ssh/authorized_keys"
            user: "{{ item.username }}"
            group: "{{ item.username }}"
            mode: "0644"
            remote_src: True
            with_items: "{{ users }}"
